name: SFDX-CLI Deploy from Repository
on: [push]
jobs:
  SFDX-CLI-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🐧 GitHub Action running on ${{ runner.os }}"
      - run: echo "🔎 Retrieving ${{ github.ref }} from ${{ github.repository }}."
      - uses: actions/checkout@v2
      - run: npm install sfdx-cli -g
      - run: echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'ruleset.xml'
          analyzeModifiedFilesOnly: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: pmd-report.sarif
      - run: sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --setdefaultdevhubusername
      - run: sfdx force:source:deploy --manifest=manifest/package.xml --testlevel=RunLocalTests -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME }}
