name: SFDX-CLI Deploy from Repository
on:
  pull_request:
    types:
      - closed

jobs:
  SFDX-CLI-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🐧 GitHub Action running on ${{ runner.os }}"
      - run: echo "🔎 Retrieving ${{ github.ref }} from ${{ github.repository }}."
      - uses: actions/checkout@v2
      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli
          npx sf plugins install @salesforce/sfdx-scanner
      - name: Run SFDX CLI Scanner
        run: |
          sf scanner:run -f html -t "force-app" -e "eslint,retire-js,pmd,cpd" -c "Design,Best Practices,Code Style,Performance,Security" --outfile ./reports/scan-reports.html
      - run: echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
      - run: sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --setdefaultdevhubusername
      - run: sfdx force:source:deploy --manifest=manifest/package.xml -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME }}
